name: Set PR Status
description: 'Sets a status check on a pull request'

inputs:
  status:
    description: 'Status to set (success, failure, pending, error)'
    required: true
    type: string
  context:
    description: 'Context name for the status (e.g., "ci/tests", "ci/lint")'
    required: true
    type: string
  description:
    description: 'Description of the status'
    required: true
    type: string
  target_url:
    description: 'URL to link to from the status (optional)'
    required: false
    type: string
  sha:
    description: 'Git SHA to set the status on'
    required: true
    type: string
  github_token:
    description: 'GitHub token with appropriate permissions'
    required: true
    type: string

runs:
  using: composite
  steps:
    - name: Set PR Status
      shell: bash
      env:
        GH_TOKEN: ${{ inputs.github_token }}
      run: |
        # Set the status using GitHub CLI
        if [ -n "${{ inputs.target_url }}" ]; then
          gh api repos/${{ github.repository }}/statuses/${{ inputs.sha }} \
            --method POST \
            --field state="${{ inputs.status }}" \
            --field context="${{ inputs.context }}" \
            --field description="${{ inputs.description }}" \
            --field target_url="${{ inputs.target_url }}"
        else
          gh api repos/${{ github.repository }}/statuses/${{ inputs.sha }} \
            --method POST \
            --field state="${{ inputs.status }}" \
            --field context="${{ inputs.context }}" \
            --field description="${{ inputs.description }}"
        fi

        echo "✅ Status '${{ inputs.status }}' set for context '${{ inputs.context }}'"
