name: Contributor actions

on:
  pull_request_target:
    types: [opened, synchronize, reopened]
    branches: [main]

jobs:
  contributor-actions:
    name: Setup actions with secrets
    runs-on: ubuntu-latest
    permissions:
      statuses: write
    strategy:
      matrix:
        include:
          - description: 'Core Package Tests'
          - description: 'MCP Package Tests'
          - description: 'E2E Tests'
          - description: 'Combined store Tests (vector+storage)'
          - description: 'Memory Tests'
          - description: 'RAG Tests'
          - description: 'Tool Builder Tests'
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
      - name: Setup custom action
        uses: ./.github/workflows/shared-actions/set-pr-status
        with:
          status: 'pending'
          context: ${{ matrix.description }}
          sha: ${{ github.event.pull_request.head.sha }}
          github_token: ${{ secrets.GITHUB_TOKEN }}
