name: Core Package Tests

on:
  workflow_run:
    workflows: ['Quality assurance']
    types:
      - completed

jobs:
  check-changes:
    if: ${{ github.repository == 'mastra-ai/mastra' }}
    runs-on: ubuntu-latest
    outputs:
      core-changed: ${{ steps.changes.outputs.core }}
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v4

      - name: Check for core package changes
        uses: dorny/paths-filter@v3
        id: changes
        with:
          base: main
          filters: |
            core:
              - 'packages/core/**'

  skip-tests:
    needs: check-changes
    if: needs.check-changes.outputs.core-changed == 'false'
    runs-on: ubuntu-latest
    permissions:
      statuses: write
    steps:
      - name: Set success status for unchanged core
        uses: ./.github/workflows/shared-actions/set-pr-status
        with:
          status: 'success'
          context: 'Core Package Tests'
          description: 'Core package unchanged - skipping tests'
          sha: ${{ github.event.workflow_run.head_sha }}
          github_token: ${{ secrets.GITHUB_TOKEN }}

  test:
    needs: check-changes
    if: needs.check-changes.outputs.core-changed == 'true'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: pnpm/action-setup@v4
        name: Install pnpm
        with:
          run_install: false

      - name: Setup Node.js 20.x
        uses: actions/setup-node@v4
        with:
          node-version: 20.19.1
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install

      - name: Build cli
        run: pnpm build:core

      - name: Run Core tests
        run: pnpm test:core
        env:
          NODE_OPTIONS: '--max_old_space_size=8096'
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}

  test-success:
    needs: [check-changes, test]
    if: ${{ always() && needs.check-changes.outputs.core-changed == 'true' && needs.test.result == 'success' }}
    runs-on: ubuntu-latest
    permissions:
      statuses: write
    steps:
      - uses: actions/checkout@v4
      - name: Set success status for completed tests
        uses: ./.github/workflows/shared-actions/set-pr-status
        with:
          status: 'success'
          context: 'Core Package Tests'
          description: 'All core tests passed'
          sha: ${{ github.event.workflow_run.head_sha }}
          github_token: ${{ secrets.GITHUB_TOKEN }}
          target_url: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}

  test-failure:
    needs: [check-changes, test]
    if: ${{ always() && needs.check-changes.outputs.core-changed == 'true' && needs.test.result == 'failure' }}
    runs-on: ubuntu-latest
    permissions:
      statuses: write
    steps:
      - uses: actions/checkout@v4
      - name: Set failure status for failed tests
        uses: ./.github/workflows/shared-actions/set-pr-status
        with:
          status: 'failure'
          context: 'Core Package Tests'
          description: 'Core tests failed'
          sha: ${{ github.event.workflow_run.head_sha }}
          github_token: ${{ secrets.GITHUB_TOKEN }}
          target_url: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}
